sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creatinf an image with dockerfile"
  - docker build -t chaeyeon2367/docker-react-app -f Dockerfile.dev . 
script:
  - docker run -e CI=true chaeyeon2367/docker-react-app npm run test -- --coverage

deploy:
    provider : elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react-app"
    env: "Dockerreactapp-env"
    bucket_name: "elasticbeanstalk-eu-west-3-806204255787"
    bucket_path: "elasticbeanstalk-eu-west-3-806204255787"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
