sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creatinf an image with dockerfile"
  - docker build -t chaeyeon2367/docker-react-app -f Dockerfile.dev . 
script:
  - docker run -e CI=true chaeyeon2367/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

